config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  devise_for :users
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: :comments_count
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :user_id, presence: true
  validates :tweet_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :destroy
  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, ImageUploader
  has_many :tweets
  has_many :comments
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: :index

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comments, only: [:edit, :update, :destroy]

  before_action :set_tweets

  def new
    @comments = Comment.new
  end

  def create
    @comments = Comment.new(comments_params)
    if @comments.save
      redirect_to tweet_path(@tweets)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comments.update(comments_params)
      redirect_to tweet_path(@tweets)
    else
      render 'edit'
    end
  end

  def destroy
    @comments.destroy
    redirect_to tweet_path(@tweets)
  end

  private

  def comments_params
    params.require(:comment).permit(:comment, :comments).merge(tweet_id: params[:tweet_id], user_id: current_user.id)
  end

  def set_comments
    @comments = Comment.find(params[:id])
  end

  def set_tweets
    @tweets = Tweet.find(params[:tweet_id])
  end

  def set_users
    @users = User.find(params[:user_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @like = Like.create(user_id: current_user.id, tweet_id: @tweet.id)
    @like_hash ={}

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    like = Like.find_by(user_id: current_user.id, tweet_id: @tweet.id)
    like.destroy
    @like_hash = {}

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @users = User.find(params[:followed_id])
    current_user.follow(@users)
    respond_to do |format|
      format.html { redirect_to @users }
      format.js
    end
  end

  def destroy
    @users = Relationship.find(params[:id]).followed
    current_user.unfollow(@users)
    respond_to do |format|
      format.html { redirect_to @users }
      format.js
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweets, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(10)
    if user_signed_in?
      @like_hash = Like.where(user_id: current_user.id).pluck(:id, :tweet_id).to_h
    end
  end

  def show
    @comments = @tweets.comments.includes(:user)
    @comments = @comments.order("created_at DESC").page(params[:page]).per(10)
    if user_signed_in?
      @like_hash = Like.where(user_id: current_user.id).pluck(:id, :tweet_id).to_h
    end
  end

  def new
    @tweets = Tweet.new
  end

  def create
    @tweets = Tweet.new(tweets_params)
    if @tweets.save
      redirect_to tweets_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @tweets.update(tweets_params)
      redirect_to tweets_path
    else
      render 'edit'
    end
  end

  def destroy
    @tweets.destroy
    redirect_to tweets_path
  end

  private

  def tweets_params
    params.require(:tweet).permit(:title, :text).merge(user_id: current_user.id)
  end

  def set_tweets
    @tweets = Tweet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_users

  def show
    @tweets = @users.tweets
    @tweets = @tweets.order("created_at DESC").page(params[:page]).per(10)
    @comments = @users.comments.includes(:tweet)
    if user_signed_in?
      @like_hash = Like.where(user_id: current_user.id).pluck(:id, :tweet_id).to_h
    end
  end

  def edit
  end

  def update
    if @users.update(users_params)
      redirect_to user_path(@users)
    else
      render 'edit'
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def users_params
    params.require(:user).permit(:nickname, :email, :image)
  end

  def set_users
    @users = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@tweets, @comments] do |f| %>
  <div class="form-signin mt-5">
    <h1 class="h3 mb-3 font-weight-normal text-center">スレッドへのコメント</h1>
    <%= f.label "コメントする", class: "sr-only" %>
    <%= f.text_area :comments, class: "form-control mb-2", style: "resize: none;", placeholder: "コメントを入力" %>
    <%= f.submit "送信", class: "btn btn-lg btn-danger btn-block" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render 'comments/form' %>

app/views/comments/new.html.erb
<%= render 'comments/form' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light sticky-top">
  <div class="container">
    <%= link_to tweets_path do %>
      <%= image_tag "15301066352625988.png", size: "250x60" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon bg-secondary"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <% if user_signed_in? %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "oi oi-account-logout btn-outline-danger btn-lg btn-primary" %>
              <%= link_to 'マイページ', user_path(current_user.id), class: "oi oi-person btn-outline-danger btn-lg btn-primary" %>
          <% else %>
              <%= link_to 'ログイン', new_user_session_path, class: "oi oi-account-login btn-outline-danger btn-lg btn-primary" %>
              <%= link_to '新規登録', new_user_registration_path, class: "oi oi-heart btn-outline-danger btn-lg btn-primary" %>
          <% end %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <%= link_to '投稿する', new_tweet_path, class: "btn-outline-danger btn-lg btn-primary oi oi-pencil text-center" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CherryNote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <link href="/font/css/open-iconic-bootstrap.css" rel="stylesheet">
    <!-- open-iconic-bootstrap (icon set for bootstrap) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />

    <script>
      FontAwesomeConfig = { searchPseudoElements: true };
    </script>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= yield %>

  </body>
</html>

app/views/likes/_like.html.erb
け<% if user_signed_in? %>
  <% if @like_hash.has_value?(tweet.id) %>
    <%= link_to 'いいねを消す', tweet_like_path(tweet.id, @like_hash.key(tweet.id)), class:'fas fa-heart text-danger float-left', method: :delete, id: "like-button", remote: true %>
    <span class="text-danger float-left ml-1">
      <%= tweet.likes_count %>
    </span>
  <% else %>
    <%= link_to 'いいねする', tweet_likes_path(tweet_id: tweet.id), method: :post, class: 'far fa-heart text-danger float-left', id: "like-button", remote: true %>
    <span class="text-danger float-left ml-1">
      <%= tweet.likes_count %>
    </span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like_<%= @tweet.id %>").html("<%= j(render 'likes/like', {tweet:@tweet}) %>");

app/views/likes/destroy.js.erb
$("#like_<%= @tweet.id %>").html("<%= j(render 'likes/like', {tweet:@tweet}) %>");

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @users.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @users.followers.count %>');

app/views/tweets/_comments.html.erb
<div class="card text-center w-75 mt-5 mb-5 mx-auto">
  <div class="card-header">
    <div class="float-left">
      <% if comment.user.image.nil? %>
        <%= image_tag "assets/071-01.png", size: "45x45", class: "user-image-circle" %>
      <% else %>
        <%= image_tag comment.user.image, size: "45x45", class: "user-image-circle" %>
      <% end %>
      <%= link_to "#{comment.user.nickname}さんのコメント", user_path(comment.user.id) %>
    </div>
    <div class="float-right">
      <div class="dropdown">
        <a class="oi oi-ellipses dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% if user_signed_in? && comment.user.id == current_user.id %>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to '編集', "/tweets/#{@tweets.id}/comments/#{comment.id}/edit" %></li>
              <li><%= link_to '削除', "/tweets/#{@tweets.id}/comments/#{comment.id}", method: :delete %></li>
            </ul>
          <% else %>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to "#{comment.user.nickname}さんのマイページ", user_path(comment.user.id) %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <p class="card-text"><%= comment.comments %></p>
  </div>
  <div class="card-footer text-muted">
    <%= link_to "#{comment.user.nickname}さんのマイページ", user_path(comment.user.id) %>
  </div>
</div>

app/views/tweets/_form.html.erb
<%= form_for (@tweets) do |f| %>
  <div class="form-signin mt-5">
    <h1 class="h3 mb-3 font-weight-normal text-center">スレッドの投稿</h1>
    <%= f.label :title, class: "sr-only" %>
    <%= f.text_area :title, maxlength: "40", class: "form-control mb-2", style: "resize: none;", placeholder: "タイトル(40文字以内)" %>
    <%= f.label :text, class: "sr-only" %>
    <%= f.text_area :text, class: "form-control mb-2", style: "resize: none;", placeholder: "スレッドの内容" %>
    <%= f.submit "投稿する", class: "btn btn-lg btn-danger btn-block" %>
  </div>
<% end %>

app/views/tweets/_thread.html.erb
<div class="card text-center w-75 m-5 mx-auto">
  <div class="card-header">
    <div class="float-left">
      <% if @tweets.user.image.nil? %>
        <%= link_to user_path(@tweets.user.id) do %>
          <%= image_tag "assets/071-01.png", size: "45x45", class: "user-image-circle" %>
        <% end %>
      <% else %>
        <%= link_to user_path(@tweets.user.id) do %>
          <%= image_tag @tweets.user.image, size: "45x45", class: "user-image-circle" %>
        <% end %>
      <% end %>
      <%= link_to "#{@tweets.user.nickname}さんの投稿", user_path(@tweets.user.id) %>
    </div>
    <div class="float-right">
      <div class="dropdown">
        <a class="oi oi-ellipses dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% if user_signed_in? && @tweets.user.id == current_user.id %>
            <ul>
              <li><%= link_to '編集', edit_tweet_path(@tweets) %></li>
              <li><%= link_to '削除', tweet_path(@tweets), method: :delete %></li>
            </ul>
          <% else %>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to "#{@tweets.user.nickname}さんのマイページ", user_path(@tweets.user.id) %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title" style="font-weight: bold;"><%= @tweets.title %></h5>
    <p class="card-text"><%= @tweets.text %></p>
  </div>
  <div class="card-footer text-muted">
    <div id="like_<%= @tweets %>">
      <%= render partial: "likes/like", locals: {tweet: @tweets} %>
    </div>
    <%= link_to 'コメント', new_tweet_comment_path(@tweets), class: "fas fa-reply text-info float-left ml-3" %>
    <span class="text-info float-left ml-1">
      <%= @tweets.comments_count %>
    </span>
    <%= social_share_button_tag(@tweets.title) %>
  </div>
</div>

app/views/tweets/_tweets.html.erb
<div class="card text-center w-75 mt-5 mb-5 mx-auto">
  <div class="card-header">
    <div class="float-left">
      <% if tweet.user.image.nil? %>
        <%= link_to user_path(tweet.user.id) do %>
          <%= image_tag "assets/071-01.png", size: "45x45", class: "user-image-circle" %>
        <% end %>
      <% else %>
        <%= link_to user_path(tweet.user.id) do %>
          <%= image_tag tweet.user.image, size: "45x45", class: "user-image-circle" %>
        <% end %>
      <% end %>
      <%= link_to "#{tweet.user.nickname}さんの投稿", user_path(tweet.user.id) %>
    </div>
    <div class="float-right">
      <div class="dropdown">
        <a class="oi oi-ellipses dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% if user_signed_in? && tweet.user.id == current_user.id %>
            <ul>
              <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>
              <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
            </ul>
          <% else %>
            <ul>
              <li><%= link_to "#{tweet.user.nickname}さんのマイページ", user_path(tweet.user.id) %></li>
              <li><%= link_to 'スレッドを見る', tweet_path(tweet.id) %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div id="tweet_<%= tweet.id %>">
    <div class="card-body">
      <h5 class="card-title" style="font-weight: bold;"><%= tweet.title %></h5>
      <p class="card-text"><%= tweet.text %></p>
      <%=  link_to 'スレッドを見る', tweet_path(tweet.id) %>
    </div>
    <div class="card-footer text-muted">
      <div id="like_<%= tweet.id %>">
        <%= render partial: "likes/like", locals: {tweet: tweet} %>
      </div>
      <%= link_to 'コメント', new_tweet_comment_path(tweet.id), class: "fas fa-reply text-info float-left ml-3" %>
      <span class="text-info float-left ml-1">
        <%= tweet.comments_count %>
      </span>
      <%= social_share_button_tag(tweet.title) %>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'tweets/form' %>

app/views/tweets/index.html.erb
<% @tweets.each do |tweet| %>
  <%= render partial: 'tweets/tweets', locals: {tweet: tweet} %>
<% end %>

<div class="mx-auto w-75">
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<%= render 'tweets/form' %>

app/views/tweets/show.html.erb
<!-- スレッド -->

<%= render 'tweets/thread' %>

<!-- リプライ -->

<% @comments.each do |comment| %>
  <%= render partial: 'tweets/comments', locals: {comment: comment} %>
<% end %>

<div class="card card-body mx-auto w-75 mb-5">
  <%= link_to 'このスレッドにコメントする', new_tweet_comment_path(@tweets), class: "btn-outline-danger btn-lg btn-primary fas fa-reply text-center" %>
</div>


<div class="mx-auto w-75">
  <%= paginate(@comments) %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @users.id %></div>
  <%= f.submit 'フォロー', class: "btn-outline-primary btn mt-3" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @users %>
  <div id="follow_form">
  <% if current_user.following?(@users) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_mypage.html.erb
<div class="card text-center w-75 mt-5 mb-5 mx-auto">
  <div class="card-header">
    <p style="font-weight: bold;"><%= link_to "#{@users.nickname}さんのマイページ", user_path(@users) %></p>
  </div>
  <div class="card-body">
    <% if @users.image.nil? %>
      <%= link_to edit_user_path(@users) do %>
        <%= image_tag "assets/071-01.png", size: "100x100", class: "user-image-circle mb-2" %>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(@users) do %>
        <%= image_tag @users.image, size: "100x100", class: "user-image-circle mb-2" %>
      <% end %>
    <% end %>
    <%= render 'stats' %>
    <%= render 'follow_form' %>
  </div>
  <div class="card-footer text-muted">
    <% if user_signed_in? && @users.id == current_user.id %>
      <%= link_to 'マイページの編集', edit_user_path(@users) %>
    <% end %>
  </div>
</div>

app/views/users/_stats.html.erb
<% @users ||= current_user %>
<div class="stats">
  <%= link_to "フォロー#{@users.following.count}", following_user_path(@users) %>
  <%= link_to "フォロワー#{@users.followers.count}", followers_user_path(@users) %>
</div>

app/views/users/_tweets.html.erb
<div class="card text-center w-75 m-5 mb-5 mx-auto">
  <div class="card-header">
    <div class="float-left">
      <% if tweet.user.image.nil? %>
        <%= link_to user_path(tweet.user.id) do %>
          <%= image_tag "assets/071-01.png", size: "45x45", class: "user-image-circle" %>
        <% end %>
      <% else %>
        <%= link_to user_path(tweet.user.id) do %>
          <%= image_tag tweet.user.image, size: "45x45", class: "user-image-circle" %>
        <% end %>
      <% end %>
      <%= link_to "#{tweet.user.nickname}さんの投稿", user_path(tweet.user.id) %>
    </div>
    <div class="float-right">
      <div class="dropdown">
        <a class="oi oi-ellipses dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% if user_signed_in? && tweet.user.id == current_user.id %>
            <ul>
              <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>
              <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
            </ul>
          <% else %>
            <ul>
              <li><%= link_to "#{tweet.user.nickname}さんのマイページ", user_path(tweet.user.id) %></li>
              <li><%= link_to 'スレッドを見る', tweet_path(tweet.id) %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title" style="font-weight: bold;"><%= tweet.title %></h5>
    <p class="card-text"><%= tweet.text %></p>
    <%=  link_to 'スレッドを見る', tweet_path(tweet.id) %>
  </div>
  <div class="card-footer text-muted">
      <div id="like_<%= tweet.id %>">
        <%= render partial: "likes/like", locals: {tweet: tweet} %>
      </div>
      <%= link_to 'コメント', new_tweet_comment_path(tweet.id), class: "fas fa-reply text-info float-left ml-3" %>
      <span class="text-info float-left ml-1">
        <%= tweet.comments_count %>
      </span>
      <%= social_share_button_tag(tweet.title) %>
    </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @users.id),
 html: { method: :delete },
 remote: true) do |f| %>
  <%= f.submit 'リムーブ', class: "btn-outline-dark btn mt-3" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@users) do |f| %>
  <div class="form-signin" style="margin-top: 40px;">
    <h1 class="h3 mb-3 font-weight-normal text-center">マイページ</h1>
    <%= f.label :image, "プロフィール画像", class: "oi oi-camera-slr btn btn-outline-danger btn-block mb-2" %>
    <%= f.file_field :image, class: "btn btn-outline-danger btn-block mb-2" %>
    <%= f.label :ニックネーム, class: "sr-only" %>
    <%= f.text_field :nickname, autofocus: true, autocomplete: "ニックネーム", class: "form-control mb-2", id: "inputPassword", placeholder: "ニックネームを入力" %>
    <%= f.label :メールアドレス, class: "sr-only" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control mb-2", id: "inputEmail", placeholder: "メールアドレスを入力" %>
    <%= f.submit "更新", class: "btn btn-lg btn-danger btn-block" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render 'mypage' %>

<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true"><%= @users.nickname %>さんの投稿一覧</a>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
    <% @tweets.each do |tweet| %>
      <%= render partial: 'tweets', locals: {tweet: tweet} %>
    <% end %>
  </div>
</div>

<div class="mx-auto w-75">
  <%= paginate(@tweets) %>
</div>

app/views/users/show_follow.html.erb
<% @user.following.each do |user| %>
  <div class="card text-center w-75 mt-5 mb-5 mx-auto">
    <div class="card-header">
      <p style="font-weight: bold;"><%= link_to "#{user.nickname}さんのマイページ", user_path(user) %></p>
    </div>
    <div class="card-body">
      <% if user.image.nil? %>
        <%= link_to edit_user_path(user) do %>
          <%= image_tag "assets/071-01.png", size: "100x100", class: "user-image-circle mb-2" %>
        <% end %>
      <% else %>
        <%= link_to edit_user_path(user) do %>
          <%= image_tag user.image, size: "100x100", class: "user-image-circle mb-2" %>
        <% end %>
      <% end %>
    </div>
    <div class="card-footer text-muted">
      <% if user_signed_in? && user.id == current_user.id %>
        <%= link_to 'マイページの編集', edit_user_path(user) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
  <div class="card text-center w-75 mt-5 mb-5 mx-auto">
    <div class="card-header">
      <p style="font-weight: bold;"><%= link_to "#{user.nickname}さんのマイページ", user_path(user) %></p>
    </div>
    <div class="card-body">
      <% if user.image.nil? %>
        <%= link_to edit_user_path(user) do %>
          <%= image_tag "assets/071-01.png", size: "100x100", class: "user-image-circle mb-2" %>
        <% end %>
      <% else %>
        <%= link_to edit_user_path(user) do %>
          <%= image_tag user.image, size: "100x100", class: "user-image-circle mb-2" %>
        <% end %>
      <% end %>
    </div>
    <div class="card-footer text-muted">
      <% if user_signed_in? && user.id == current_user.id %>
        <%= link_to 'マイページの編集', edit_user_path(user) %>
      <% end %>
    </div>
  </div>
<% end %>